services:
  # Reverse Proxy Service
  nginx:
    image: nginx:alpine
    container_name: filesox_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  postgres:
    image: postgres:17.4-alpine
    container_name: filesox_database
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: filesox
      POSTGRES_USER: filesox
      POSTGRES_PASSWORD: filesox
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./storage-db:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis Service
  redis:
    image: redis:latest
    container_name: filesox_redis
    restart: unless-stopped
    command: redis-server --requirepass filesox-redis
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      REDIS_PASSWORD: filesox-redis
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge